### ISSUE TITLE
SeFa vectors must be used in W-space

### ISSUE THREAD

**Issue by vlfom** [dvschultz/stylegan2-ada-pytorch#14]
Dear authors, thank you for the great work and accompanying videos, they are very helpful.

**Describe the bug**
I believe the SeFa-discovered latent directions should be used to alter the latent vectors from the W-space, while the code seems to use them in the Z-space: https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/apply_factor.py#L37.

**Expected behavior**
According to the SeFa authors' code, for StyleGan2 the eigenvectors are used to alter the Ws: https://github.com/genforce/sefa/blob/master/interface.py#L53.

In any case, interestingly, the visual results from applying eigenvectors in Z-space _kind of_ correlate with W-space ones.

**Comment by dvschultz** [comment]
Yeah, if I’m reading this correctly they still generate the factors from the z space, they just convert the output images to w space before rendering. So you’ll see only minor changes to the actual outputs. Where you might see bigger changes is in an interpolation—this might disentagle the space better making it easier to interpret what the factor actually alters.

I’ll add this option shortly. Thanks for noticing it.

**Comment by dvschultz** [comment]
Fixed. By default apply_factor.py will use W space.
