### ISSUE TITLE
Transfer Learning fails when training 256 resolution model based on custom dataset

### ISSUE THREAD

**Issue by LLSean** [dvschultz/stylegan2-ada-pytorch#15]
Hi, I have prepared my dataset according to dataset_tool.py and set datasets width and height to 256x256. Here is the problem: When running python train.py and my Transfer Learning source network is ffhq256 the execution fails pretty soon (in the beginning of "Constructing networks") with this error: RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 1.What is the problem here? Thanks in advance! PS: I also tried ffhq512 and it can train the model, but the output model's structure is ffhq256, so I'm very confused.

**Comment by dvschultz** [comment]
what it your training command? is the correct resolution printed to the console during the setup?

**Comment by LLSean** [comment]
> what it your training command? is the correct resolution printed to the console during the setup?

I solved it.My training parameter is wrong.When I choose paper256 config,it works!Thanks
