### ISSUE TITLE
how to convert .pkl to .pt

### ISSUE THREAD

**Issue by leeisack** [dvschultz/stylegan2-ada-pytorch#20]
I want to change the pkl file learned through stylegan2-ada to a pt file, but I would like to explain it in more detail. For example in SG2-ADA-PT to Rosinality.ipynb !python export_weights.py /path/to/pkl /path/to/saved.pt in this code {/path/to/pkl /path/to/saved. pt } It would be nice if you could tell me an example to put here.

**Comment by dvschultz** [comment]
the first argument is your path to a pkl file, the second argument is where to save your pt file

Example:
`!python export_weights.py /content/mymodel.pkl /content/mymodel-converted.pt`
